### ISSUE TITLE
Some questions about Surrounding text?

### ISSUE THREAD

**Issue by trmdi** [fcitx/fcitx5-unikey#13]
Hi, I have some questions:

1, Can fcitx get surrounding text in all cases? e.g. Qt, Gtk, Firefox, Chrome, X11, Wayland... How reliable is it?
2, Is it possible to modify the surrounding text in all cases?

If so, we can make more use of that approach which is better, for example:

- commit right after each key event. This is good for e.g. browser's suggestion. Currently auto commit is only applied to some characters, not all.
- modify any word at the cursor at any time
- ...

**Comment by wengxt** [comment]
There are a good amount of applications that would never work with it. For example, xim based client doesn't work (xterm, wine, etc), SDL application. Terminals are also a good case if you just think about it.

It can also be buggy in certain applications if they are not using system built-in widget, especially for browser. Also, if webages is messing around with how text is displayed (google docs), it may not work there too. And that is pretty bad because we can not check against application's version even if we managed to fix them in some cases. Certain hack can be done by checking application name, but the name of application may not be available under certain cases depending on what protocol is used. Also, embedded terminal window (e.g. konsolepart) is a case where the application name detection workaround fails.

It can be a nice source of supplement of information, but I'd rather not rely on it for everything. For example,
- Japanese usually only use it for "reconvert" (selecting a range of hiragana character and re-initiate the composing with selected text)
- Hangul also only use it for temporary Hanja mode, but it also provides an always-on Hanja mode which won't use surrounding at all (Somewhat similar to macro mode in unikey).
- In Chinese I use it in certain cases just to detect the context and not modify the surrounding text

In a word, using the information from surrounding is more reliable than modifying the surrounding text, and it would be better to have an easy way (in the sense of user may figure out an alternative way of typing text really easily) to workaround it when it's not working properly.

Also whether we can use it or not depends on whether the underlying library can support it well.

**Comment by wengxt** [comment]
close because not a bug.

Also, FYI for some on-going bug about surrounding text, which is really a good example why surrounding text is never reliable.

https://gitlab.gnome.org/GNOME/mutter/-/issues/2146
Also gtk text input v3 doesn't send surrounding as frequently as it should.

**Comment by trmdi** [comment]
What do you think about modifying a committed word by deleting that word then convert it into a preedit one?
I just found there is a method for deleting surrounding text:
https://github.com/fcitx/fcitx5/blob/9aece8e706812f1d18b6448a761f3c4fde73ebcd/src/lib/fcitx/inputcontext.h#L164
Is this method reliable in Qt and Gtk?

**Comment by wengxt** [comment]
> What do you think about modifying a committed word by deleting that word then reinsert it as a preedit one? I just found there is a method for deleting surrounding text: https://github.com/fcitx/fcitx5/blob/9aece8e706812f1d18b6448a761f3c4fde73ebcd/src/lib/fcitx/inputcontext.h#L164
> 
> ```
> void deleteSurroundingText(int offset, unsigned int size);
> ```
> 
> Is this method reliable in Qt and Gtk?

I'm ok if we want to implement it, but I probably won't enable it by default on Linux. The method is "supposed" to be supported as long as CapabilityFlag has SurroundingText bit.
https://www.csslayer.info/wordpress/fcitx-dev/why-surrounding-text-is-the-worst-feature-in-the-linux-input-method-world/

**Comment by zenfas** [comment]
@wengxt On Android, it's better, I see most of app support it. If fcitx can support it, fcitx5-android is very good

**Comment by trmdi** [comment]
Chromium, Libreoffice don't support SurroundingText? That's sad.

**Comment by zenfas** [comment]
> @wengxt Chromium, Libreoffice don't support SurroundingText? That's sad.

Not much people take care surrounding text on GTK/QT or text-input protocol on upstreams, I see some bug reports of Mr Weng don't have response :(

**Comment by ermshiperete** [comment]
> Chromium, Libreoffice don't support SurroundingText?

LibreOffice DOES support surrounding text. Chromium doesn't.

**Comment by wengxt** [comment]
@ermshiperete it depends, libreoffice can be run with either Qt or Gtk and it will go with gtk im module, or qt im module. Apparently, the Qt version doesn't do it correctly.

`OOO_FORCE_DESKTOP=gnome` and `OOO_FORCE_DESKTOP=kde` may gives you different result. You'll need to install corresponding libreoffice package too, some distro may split it into things like libreoffice-kde{xx}

**Comment by trmdi** [comment]
> Apparently, the Qt version doesn't do it correctly.

yes, I'm using the KDE version. You mean this is a LibreOffice bug or a fcitx5-qt bug?

**Comment by wengxt** [comment]
> > Apparently, the Qt version doesn't do it correctly.
> 
> yes, I'm using the KDE version. You mean this is a LibreOffice bug or a fcitx5-qt bug?

libreoffice bug since it works in other qt app.

App like libreoffice would need to re-implement their own input method support for their widget, can't use Qwidget version directly.

**Comment by trmdi** [comment]
Pretty cool. :D

![fcitx5-2022-11-26_00 03 03](https://user-images.githubusercontent.com/11857205/204030455-8c582b9f-e73d-4ab1-a298-e1728a96077c.gif)

**Comment by zenfas** [comment]
> Pretty cool. :D
> 
> ![fcitx5-2022-11-26_00 03 03](https://user-images.githubusercontent.com/11857205/204030455-8c582b9f-e73d-4ab1-a298-e1728a96077c.gif) [ ![fcitx5-2022-11-26_00 03 03](https://user-images.githubusercontent.com/11857205/204030455-8c582b9f-e73d-4ab1-a298-e1728a96077c.gif) ](https://user-images.githubusercontent.com/11857205/204030455-8c582b9f-e73d-4ab1-a298-e1728a96077c.gif) [ ](https://user-images.githubusercontent.com/11857205/204030455-8c582b9f-e73d-4ab1-a298-e1728a96077c.gif)

I see it didn't detect whole word, maybe will have error in some cases with Spell check and Auto restore invalid turn on

**Comment by trmdi** [comment]
> I'm ok if we want to implement it,

https://github.com/fcitx/fcitx5-unikey/pull/34
