### ISSUE TITLE
The submenu is shown wrongly on the first time

### ISSUE THREAD

**Issue by trmdi** [fcitx/fcitx5-unikey#8]
Please see the screenshot:
![image](https://user-images.githubusercontent.com/11857205/141038295-036d8933-29d3-4900-a4c0-92b09b818944.png)

If you hide then show it again, it appears properly.
![image](https://user-images.githubusercontent.com/11857205/141038434-a8642848-47ca-4b3f-bfad-57718707e3e8.png)

I'm using the latest Qt on openSUSE Tumbleweed.

**Comment by wengxt** [comment]
Ok, I kinda get what you mean here, you are saying that the sub menu is not properly positioned when it was first displayed right?

Unfortunately this is an issue with KDE's SNI and submenu. And there's nothing I can do from fcitx side. I can easily reproduce the similar issue with some other application with tray menu e.g. kalarm. I think this is mainly because KDE only request one level of menu and the "aboutToShow" doesn't have time to properly calculate the size of menu before it's shown.
